apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  namespace: devops
spec:
  replicas: 1

  selector:
    matchLabels:
      app: devops-api

  template:
    metadata:
      labels:
        app: devops-api

    spec:
      containers:
        - name: devops-api
          image: ghcr.io/sara-aitaami/devops-deploy-platform:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: devops-api
  namespace: devops
  labels:
    app: devops-api

spec:
  selector:
    app: devops-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

  type: NodePort